enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/revanced-integrations"
rv-brand = "YT-Advanced ReVanced"
included-patches = "'Add splash animation' 'MaterialYou'"
excluded-patches = "'Custom branding heading' 'Custom branding icon YouTube' 'Custom branding name YouTube'"
